### ISSUE TITLE
Units for quantities in bpp and bcm arrays

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#102]
It would be nice to have somewhere in the docs what the units for all the quantities in the bpp and bcm arrays are. 

One thing I'd like to know asap, if possible, is if the `sep` in the bpp array is in AU or Rsun.

**Comment by katiebreivik** [comment]
The docs:
https://cosmic-popsynth.github.io/examples/index.html#single-binary have
units. Separations are in solar radii.

**Comment by michaelzevin** [comment]
I'm an idiot. Thanks!
