### ISSUE TITLE
check that all flags are set properly

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#104]
JEff Andrews showed us that the way you initialize the common block variables matters! 

We need to check all of the flags that are declared in common blocks are declared properly (as int if they are int or float if they are float).

**Comment by scottcoughlin2014** [comment]
To add to this issue we need to squash all of the times this happens

```
cosmic/src/zfuncs.f: In function ‘celamf’:
cosmic/src/zfuncs.f:962:0: warning: ‘lam2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             celamf = lam2 + sqrt(menv)*(lam1 - lam2)
 ^
cosmic/src/zfuncs.f:962:0: warning: ‘lam1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```

**Comment by scottcoughlin2014** [comment]
I think that #119 and this are both the same issue. The upcoming PR will address a good chunk of warnings or possible problems. After that we have just a few more to follow up on listed in #119

**Comment by michaelzevin** [comment]
We took care of this, closing now.
