### ISSUE TITLE
Have supernova kick magnitude and angles be optionally input to kick.f

### ISSUE THREAD

**Issue by astroJeff** [COSMIC-PopSynth/COSMIC#110]
For integrating cosmic with dart_board, there needs to be an option to pass along the SN natal kick and angles (and a second set for the second SN in double compact object binaries) from the external python call to the bse fortran executable. This would be instead of generating the kick randomly within kick.f.

**Comment by scottcoughlin2014** [comment]
Actually, I think feeding in

[vk1, phi1, theta1, vk2, phi2, theta2] is easier then my convulted plan. I think I can get that in with this upcoming PR

**Comment by katiebreivik** [comment]
This is treated in this PR: [109](https://github.com/COSMIC-PopSynth/COSMIC/pull/109)
