### ISSUE TITLE
Problem with Nanjing variable lambda prescription

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#111]
In a recent push, I decided to separate out the fixed lambda prescription so that it is implicit in comenv.f rather than buried in the two variable lambda prescriptions that are in zfuncs.f

While doing so, I found out that the nanjing lambda (XU_LI) returns utter nonsense, oftentimes giving a value of 0.0 for lambda (which is bad, since then you'll be dividing by 0.0 in the denominator when making the energy calculation). 

It doesn't seem like this variable prescription is in the CMC code whatsoever. But this is what is used by StarTrack. For now, I think it should be avoided until we find out where the issue lies.

**Comment by scottcoughlin2014** [comment]
Greater than 1 lambdaf in Params.ini should result in error after we remove this prescription.

**Comment by michaelzevin** [comment]
We should just remove Nanjing and close this issue.

**Comment by scottcoughlin2014** [comment]
#155 remove nanjing variable lambda
