### ISSUE TITLE
Critical mass ratio prescription for giants

### ISSUE THREAD

**Issue by chase-kimball** [COSMIC-PopSynth/COSMIC#113]
Just a heads up: qcrit is the critical mass ratio above which MT is unstable and CE is triggered. For giants, the [dynamical MT section of the BSE paper](http://adsabs.harvard.edu/cgi-bin/nph-data_query?bibcode=2002MNRAS.329..897H&link_type=ARTICLE&db_key=AST&high=#page=8) gives a prescription fit to "detailed stellar models", and mentions that the Webbink 88' alternative diverges from this at high Mcore/M and leads to high qcrit and hence systems avoiding CE. However, the vanilla BSE (and COSMIC) has the fit commented out and defaults to the Webbink 88' prescription:
```
      elseif(kstar(j1).eq.3.or.kstar(j1).eq.5.or.kstar(j1).eq.6)then
*        qc = (1.67d0-zpars(7)+2.d0*(massc(j1)/mass(j1))**5)/2.13d0
* Alternatively use condition of Hjellming & Webbink, 1987, ApJ, 318, 794. 
         qc = 0.362 + 1.0/(3.0*(1.0 - massc(j1)/mass(j1)))
```
May be worth looking into.

**Comment by michaelzevin** [comment]
I think it would be nice to look at what more recent literature has to say about critical mass ratios for giants...we're going through issues and closing them but I'll leave this one open for now. Maybe Tout et al. 1997 will have some pointers?

Just did a quick calculation with some basic values for Mc and M and these prescriptions are off from one another by a factor of ~2.

**Comment by scottcoughlin2014** [comment]
@chase-kimball @michaelzevin is this not taken care of with all the `qcrit` enhancements recently?

**Comment by michaelzevin** [comment]
Yes, this is taken care of with #227. Closing now.
