### ISSUE TITLE
Save People From Themselves

### ISSUE THREAD

**Issue by scottcoughlin2014** [COSMIC-PopSynth/COSMIC#116]
I think that if bin_state is 0 and a person (let's say me) happen to forget to add a `-1` to the `merger_type` list that we should either error out and tell them they want to do that or just append it on their behalf what do you think is better?

**Comment by katiebreivik** [comment]
I am personally in favor of appending on their behalf, but making a note in the log file.

**Comment by scottcoughlin2014** [comment]
Sounds good

**Comment by scottcoughlin2014** [comment]
#151 has solved this because now we do not need merge type to run anymore
