### ISSUE TITLE
typo in `LISA_SNR` when checking eccentricity

### ISSUE THREAD

**Issue by cpankow** [COSMIC-PopSynth/COSMIC#121]
This line: https://github.com/COSMIC-PopSynth/COSMIC/blob/develop/cosmic/GW_calcs.py#L184

...doesn't do what you think it does. You probably wanted to check if all values of eccentricity are below 1e-4. However, the invocation of `all` takes precedence over the check for `< 1e-4`.

```
In [1]: import numpy
In [2]: ecc = numpy.logspace(-6, -2, 10)
In [3]: ecc.all()
Out[3]: True
In [4]: ecc.all() < 1e-4
Out[4]: False
In [5]: numpy.all(ecc < 1e-4)
Out[5]: False
```

The last line is what you want. This all worked because of a numeric conversion to boolean when `.all` was called. Then you got another implicit boolean to numeric conversion for the check of True against 1e-4. Anything which is non-zero is True, and so eccentricities without zero will not trigger this.

I can submit a patch if you like, but the change is a one-liner.

**Comment by katiebreivik** [comment]
Ah. Thanks for pointing this out @cpankow! I think this will likely be overhauled in a forthcoming PR for LISA SNRs. I will be sure to keep this in mind with that PR.

**Comment by katiebreivik** [comment]
This is now handled properly-ish in this PR: https://github.com/COSMIC-PopSynth/COSMIC/pull/135
