### ISSUE TITLE
pre CE parameters are passed to kick.f in some cases

### ISSUE THREAD

**Issue by chase-kimball** [COSMIC-PopSynth/COSMIC#126]
This is an issue Mike is running into now, that I ran into years ago but never patched in Cosmic

**Comment by scottcoughlin2014** [comment]
@chase-kimball Ok great but it is a known problem. Good to know and we should definitely patch.

**Comment by chase-kimball** [comment]
Oh sorry. We were in CO group meeting and Vicky was yelling at me to create an issue

**Comment by scottcoughlin2014** [comment]
Why are you sorry for creating this issue? Definitely was good to do. Needs to be officially noted and also it alerts people paying attention to the github but not at the meeting like me!

**Comment by scottcoughlin2014** [comment]
Mike has created flags that control how you chose to pass the pre/post or whatever CE values into `kick` now.
