### ISSUE TITLE
LISA calculations might be broken with redshift calculator

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#160]
I think the redshift calculator can only handle one value at a time, so the GW calcs need to either update the redshift calculator or the whatever uses the redshift calculator

**Comment by scottcoughlin2014** [comment]
should be co-moving distance not luminosity distance

**Comment by michaelzevin** [comment]
@katiebreivik should we close this since it has been removed from the code?

**Comment by michaelzevin** [comment]
I believe this has been removed, so closing.
