### ISSUE TITLE
Error checking flags

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#170]
I've been working on a branch that does this in runFixedPop, but it would be good to have this working if you're evolving a single binary as well. Maybe error checking deserves to be its own stand-alone function? 

You can find the current version of that branch here: 
https://github.com/michaelzevin/COSMIC/tree/flag_checks

**Comment by michaelzevin** [comment]
Do this in the utils function instead: 
error_check(filters, BSEDict, convergence, randomseed):

do this for evolve.py and runFixedPop.py...

**Comment by scottcoughlin2014** [comment]
#192 fixes this
