### ISSUE TITLE
runFixedPop is not submitting a new seed for multidim sampling

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#194]
@michaelzevin found that multidim is re-running the same set of binaries for every iteration

**Comment by michaelzevin** [comment]
2801857 | 2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0
2.622568 | 131.756442 | 44.062663 | 1.0 | 1.0 | 66.096728 | 5.608325 | 0.0 | 1.000851 | 0.518058 | 3.0 | 0.0 | 0.0 | 0.0 | 0.0

**Comment by michaelzevin** [comment]
Ok @katiebreivik @scottcoughlin2014 I think I may have a fix for this. See this demo code below: 

`import multiprocessing
import numpy as np

rand_seed=5
cpus = multiprocessing.cpu_count()
print('Number of cpus: ',cpus)
# for quest I think this should just be the number of cores specified...

def f(x):
    process = multiprocessing.Process()
    #current = multiprocessing.current_process()
    #print('running:', current.name, current._identity)
    mp_seed = process._identity[0]+(cpus*(process._identity[1]-1))
    np.random.seed(rand_seed+mp_seed)
    print('unique seed: ', rand_seed+mp_seed, np.random.random())

p = multiprocessing.Pool()
p.map(f, range(10))`

`😬 michaelzevin@REM03LT013:Desktop $ python mptest.py
Number of cpus:  8
unique seed:  5 0.22199317108973948
unique seed:  6 0.8928601514360016
unique seed:  7 0.07630828937395717
unique seed:  8 0.8734294027918162
unique seed:  9 0.010374153885699955
unique seed:  13 0.7777024105738202
unique seed:  14 0.5139433437726902
unique seed:  10 0.771320643266746
unique seed:  11 0.1802696888767692
unique seed:  12 0.15416284237967237`

Moral of the story, the `Process` class has an attribute `_identity`, which returns a tuple. For me, I have 8 cores so if I run 10 jobs these look like (1,1), (2,1) ... (8,1), (1,2), (2,2). So, if `x` is the identity, we can get a consistent and unique number by the expression:
`x[0]-1 + Nproc * (x[1]-1)`

This works well on my comp, not sure how it will work on Quest though...

**Comment by michaelzevin** [comment]
I think we're in business. Here is info from the multidim sampler from two separate runs over 10 cores on Quest: 
```
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 27, 0.4257214105188958)
(7, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 29, 0.8637599855700829)
(9, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 30, 0.644143536068335)
(10, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 28, 0.7290137422891191)
(8, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 21, 0.04872488080912729)
(1, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 25, 0.8701241366272119)
(5, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 22, 0.20846053735884262)
(2, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 26, 0.30793495262497084)
(6, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 24, 0.9600173033359185)
(4, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 23, 0.5172978838465893)
(3, 1)
```

```
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 27, 0.4257214105188958)
(7, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 23, 0.5172978838465893)
(3, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 29, 0.8637599855700829)
(9, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 30, 0.644143536068335)
(10, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 28, 0.7290137422891191)
(8, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 26, 0.30793495262497084)
(6, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 21, 0.04872488080912729)
(1, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 25, 0.8701241366272119)
(5, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 22, 0.20846053735884262)
(2, 1)
('seed: ', 21)
('nproc: ', 10)
('unique seed:', 24, 0.9600173033359185)
(4, 1)
```


My changes are in #201.
