### ISSUE TITLE
tidal strength scaling factors

### ISSUE THREAD

**Issue by ageller** [COSMIC-PopSynth/COSMIC#196]
A few studies (including mine and StarTrack) have shown that the normal Hut (+BSE method) convective tides are too weak to explain observed MS-MS binary populations, at least for solar-type stars.  I’ve fudged this in my BSE code by including a scaling factor in front of the tcqr equation in evolv2.f .  For instance, in your master branch, you could include a factor for the convective damping on line 908 of evolv2.f (tcqr = fprimc * 2.d0*f*q …, where fprimc is the input scaling factor).  Likewise, for completeness, you could include factors for the radiative (line 898) and degenerate (line 915) tides, though I don’t know if observations suggest you need such factors there.  There are also additional similar tcqr equations further down in evolve2.f, around line 2800 that should also have these same scaling factors applied.  

These should be available on input from python.  Maybe you would even want this to be a function of the stellar type.

**Comment by scottcoughlin2014** [comment]
@ageller we are trying to incorporate this request before our release of the code. Wea re wrondering if just having a scaling factor is the way to go or a scaling factor array that is kstar dependent (so a like 16 vector array like we do for what q_crit value to use).

**Comment by ageller** [comment]
A kstar dependent value (input as an array) would be ideal.  Thanks.

**Comment by katiebreivik** [comment]
https://github.com/COSMIC-PopSynth/COSMIC/pull/263 fixes this
