### ISSUE TITLE
MCBAGB problem

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#202]
While diving into #195, I found some really wonky stuff is going on with the calculation of the AGB core mass in hrdiag.f. This is causing PISN to _never_ happen, since the core masses that are calculated are tiny. It also seems like for some systems, the mcbagb variable is getting set to the metallicity. 

I ran some pops of BBHs at a couple different metallicities with the PISN flag turned on/off. The initial conditions for these are saved at `/projects/b1095/michaelzevin/cosmic/examples/pisn_systems_init.hdf5` `/projects/b1095/michaelzevin/cosmic/examples/nopisn_systems_init.hdf5`
There's a script that runs the highest mass systems of these initial conditions on Quest here:
`/projects/b1095/michaelzevin/cosmic/examples/pisn_systems.py`, which has a line in it that allows you to chance the metallicity. 

Let's figure this out, since the upper mass gap and PISN are *hot* right now!

**Comment by michaelzevin** [comment]
@katiebreivik @scottcoughlin2014 I cross-checked our hrdiag.f with Carl's from CMC and I can't see anything immediately that jumps out as wrong

**Comment by michaelzevin** [comment]
[hrdiag.txt](https://github.com/COSMIC-PopSynth/COSMIC/files/3287515/hrdiag.txt)

**Comment by scottcoughlin2014** [comment]
With @michaelzevin new branch a `pisn` set to 45. I get this (when sampling initial mass1 between 100 and 200)
 seems good? I will now do it with `pisn` set to 0.
```
(Pdb) bcm.SN_1.value_counts()
0.0    25840
8.0    23760
4.0     1789
9.0      291
Name: SN_1, dtype: int64
```

**Comment by michaelzevin** [comment]
Great! That seems reasonable. @scottcoughlin2014 it would be great to see a plot of the ZAMS mass / remnant mass relation for this run, if that's not too much to ask.

**Comment by michaelzevin** [comment]
Taken care of with #208
