### ISSUE TITLE
When Nstep is too small a criteria is NEVER satisfied, causing bcm_filter to be overwritten and bcm_save never to get appended to

### ISSUE THREAD

**Issue by mkurkowski** [COSMIC-PopSynth/COSMIC#204]
When Nstep is too small a criteria is NEVER satisfied, causing `bcm_filter` to be overwritten and `bcm_save` never to get appended to. This means when Niter is too small nothing ever gets saved.
Hey @katiebreivik This is Scotty working through a student computer. I forget but I think we talked about this but shouldn't `bcm_filter` still append to `bcm_save` even if there are not 50 systems of each bin state? Otherwise is just loops forever never saving anything cuz `bcm_filter` each loop never satisfies this if statement.
Let me know!
(Also this effects out example on the docs. the Niter there is too small and no systems ever get outputted)

Scotty
```
288         n_bin_state = []
289         for bin_state in filters['binary_state']:
290             n_bin_state.append(len(bcm_filter.loc[bcm_filter.bin_state == bin_state]))
291         if all(i >= 50 for i in n_bin_state):
```

**Comment by katiebreivik** [comment]
Hey @scottcoughlin2014  - yes; this is a problem I had run into and will have a tiny pr that fixes this. Expect it tomorrow morning!

**Comment by scottcoughlin2014** [comment]
#206 fixes this
