### ISSUE TITLE
Extra columns to the BPP array.

### ISSUE THREAD

**Issue by nhtran07** [COSMIC-PopSynth/COSMIC#215]
I'm working on a project where I need the following quantities in the BPP array:
aj (effective age)
tms (MS lifetime)
massc (core mass)
rad (radius).

**Comment by katiebreivik** [comment]
Thanks @nhtran07 -- We will take a look at this soon! I am currently traveling so there is a delay but we appreciate the work!

**Comment by scottcoughlin2014** [comment]
@nhtran07 I updated the united with the new columns and have merged. Will close this now
