### ISSUE TITLE
Problems with binary fraction being hardcoded

### ISSUE THREAD

**Issue by mkurkowski** [COSMIC-PopSynth/COSMIC#218]
Instead of ending up with the same number of objects as asked for and halfish aren't in binaries.

**Comment by mkurkowski** [comment]
Be able to select which sampler is used, half vs vanhaaften, maybe pass as a kwarg?

**Comment by michaelzevin** [comment]
For evolve single binary and runfixedpop, we should be specifying how binary fraction is determined. We also need to allow arguments to change the binary fraction implementation so that it is not hardcoded. THIS IS IMPORTANT!!!

**Comment by katiebreivik** [comment]
> We also need to allow arguments to change the binary fraction implementation so that it is not hardcoded. THIS IS IMPORTANT!!!

We can't do this for the multidim sampler. Moe & Di Stefano 2017 calculates the multiplicity as a function of binary/single star parameters. If you need to have a 100% binary fraction, you will have to use the independent sampler.

**Comment by michaelzevin** [comment]
That's ok, but it would be important then to know the total binary fraction that is attained from the multidim sampler.

**Comment by scottcoughlin2014** [comment]
@katiebreivik we discussed this at the meeting Tuesday but i just realize you were not there. In the independent sampler the binary fraction is hard coded and this needs to be fixed.

```
 60     sampled_mass += total_mass1
 61     mass1_binary, mass_singles = initconditions.binary_select(mass1, model='half')
 62     mass2_binary = initconditions.sample_secondary(mass1_binary)
```

**Comment by katiebreivik** [comment]
noted, working on a PR that fixes both comments above

**Comment by katiebreivik** [comment]
https://github.com/COSMIC-PopSynth/COSMIC/pull/251 addresses this.

**Comment by michaelzevin** [comment]
@katiebreivik did this PR include writing the system-specific binary fraction as well? If not, I can open a new issue, just don't want it to slip through the cracks.

**Comment by katiebreivik** [comment]
We should open a new issue for that. It will be a different PR
