### ISSUE TITLE
porb_hi in multidim must have only one digit after the decimal?

### ISSUE THREAD

**Issue by ageller** [COSMIC-PopSynth/COSMIC#221]
Scotty added a great feature in the multidim sampler that allows us to define a maximum (and minimum) period for the sampler.  We're encountering errors whenever we try to give a porb_hi value with more than one digit after the decimal.  I'm honestly not sure why this should be a problem, but it appears to be...

**Comment by scottcoughlin2014** [comment]
@ageller so they `kwarg` porb thing I sent you is now in `develop` I also with most recent develop just tried and it worked so I think the issue is resolved and the functionality for passing custom `porb_hi` and `porb_low` will be available for `v3.0.0`
```
InitialBinaries, mass_singles, mass_binaries, n_singles, n_binaries = InitialBinaryTable.sampler('multidim', final_kstar1=[11], final_kstar2=[11], rand_seed=2, nproc=1, SFH_model='const', component_age=10000.0, met=0.02, size=10, porb_hi=4.8123)  
```
and it worked.
