### ISSUE TITLE
cosmic does not have warning for RLOF at ZAMS 

### ISSUE THREAD

**Issue by mpgalleg** [COSMIC-PopSynth/COSMIC#225]
Cosmic does not warn/restrict initial conditions that start the binary evolution in RLOF. These binaries are evolved normally even though they have unrealistic initial conditions. 

I found these binaries manually by seeing if R_star_ZAMS > R_L1 (eq 53, Hurley et al. 2002)

Here is an example: 

single_binary = InitialBinaryTable.SingleBinary(m1=10**1.5, \
                                                m2=21, \
                                                porb=0.1, \
                                                ecc=0.0, \
                                                tphysf=13700.0, \
                                                kstar1=1, \
                                                kstar2=14, \
                                                metallicity=0.002)

BSEDict = {'xi': 0.0, 'bhflag': 0.0, 'neta': 1.0, 'windflag': 3, 'wdflag': 0, 'alpha1': 1.0, 'pts1': 0.001, 
 'pts3': 0.02, 'pts2': 0.01, 'epsnov': 0.0, 'hewind': 1.0, 'ck': -1000, 'bwind': 0.0, 'lambdaf': 1.0, 'mxns': 3.0, 'beta': -1.0, 'tflag': 0.0, 'acc2': 0.0, 'nsflag': 1, 'ceflag': 0, 'eddfac': 1.0,  'ifflag': 0, 'bconst': -3000, 'sigma': 0.0, 'gamma': -2.0, 'pisn': 45,  'natal_kick_array' :[-100.0,-100.0,-100.0,-100.0,-100.0,-100.0], 'bhsigmafrac' : 1.0,   'polar_kick_angle' : 90, 'qcrit_array' : [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],   'cekickflag' : 0, 'cehestarflag' : 0, 'cemergeflag' : 0, 'ecsn' : 2.5, 'ecsn_mlow' : 1.4, 'aic' : 1,  'ussn' : 0, 'sigmadiv' :-20.0, 'ck':-1000}

**Comment by scottcoughlin2014** [comment]
@mpgalleg I am working on this now

**Comment by scottcoughlin2014** [comment]
#228 Should resolve this. Just need to it to be reviewed and approved.

**Comment by scottcoughlin2014** [comment]
It was merged
