### ISSUE TITLE
Overhead for running individual binaries

### ISSUE THREAD

**Issue by astroJeff** [COSMIC-PopSynth/COSMIC#226]
When running one binary at a time, there is some overhead involved in all the checks run and in creating the pandas data frames for each binary. For integration with dart_board or stroopwafel, this may add significant computation time to a run. It would be nice if we could produce a slimmed-down version of cosmic's fortran function call to BSE that could be efficiently integrated with external codes.

**Comment by scottcoughlin2014** [comment]
Once #358 is addressed then calling the cosmic bse module from python without the overhead will be possible (in an easier way).

**Comment by scottcoughlin2014** [comment]
@astroJeff actually helped fix this issue
