### ISSUE TITLE
bpp and bcm units are not consistent

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#232]
The radii in bpp are not in log while they are in bcm. 

Let's just make them all log10 to be consistent with the bcm

**Comment by katiebreivik** [comment]
Ok! So @michaelzevin says (actually @chase-kimball says):
 make everything not be in log - since the name isn't log_xx don't call it log.

**Comment by michaelzevin** [comment]
This is addressed in #235...closing
