### ISSUE TITLE
Eddington limited winds

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#238]
We currently don't have a way to limit winds to the Eddington limit:
<img width="335" alt="Screen Shot 2019-08-02 at 10 17 53 AM" src="https://user-images.githubusercontent.com/22921809/62380469-e654d680-b50e-11e9-9fd7-a702ab8ab5a4.png">

Mario Spera has pointed out that this is implemented in [MOBSE](https://ui.adsabs.harvard.edu/abs/2018MNRAS.474.2959G/abstract) another pop-synth code and will get rid of the weird bump at 20-30 Msun in the BH ZAMS vs formation plots that @michaelzevin  and Michael were seeing. The Eddington limit reference is [here.](https://ui.adsabs.harvard.edu/abs/2011A%26A...535A..56G/abstract)

**Comment by michaelzevin** [comment]
I coded all this up this weekend and did a few trial runs. Michael is running this on the single-star BH grid to see if things look good.

**Comment by michaelzevin** [comment]
Addressed in PR #257

**Comment by katiebreivik** [comment]
For posterity, I want to attach the wind prescription tests Michael Kurkowski did:
[wind_check.pdf](https://github.com/COSMIC-PopSynth/COSMIC/files/3486841/wind_check.pdf)

As expected, we lose the drop-off at 20-30 Msun when eddlimflag = 1, and retain it when eddlimflag = 0.
