### ISSUE TITLE
k_star requirements for runFixedPop

### ISSUE THREAD

**Issue by mpgalleg** [COSMIC-PopSynth/COSMIC#240]
Would be helpful to include in the documents a warning that kstar_1 must be greater than kstar_2 in the command line call for runFixedPop.

**Comment by katiebreivik** [comment]
Thanks @mpgalleg; we will be sure to include this in our upcoming.

**Comment by michaelzevin** [comment]
@scottcoughlin2014 just so this is on your radar

**Comment by scottcoughlin2014** [comment]
#268 makes it so that the run errors out at the command line now is you do something like ```--final-kstar1 10 --final-kstar2 11```

```
cosmic-pop: error: final-kstar1 must be greater than or equal to final-kstar2.
```
