### ISSUE TITLE
Pulsational Pair Instability black holes should get Blauuw kicks

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#242]
Something I totally didn't think about or appreciate until today. Hard pre-SN binaries can have orbital periods of up to ~1000 km/s, and the PPI ejecta leave the system at ~10000 km/s. This will give a very significant mass-loss kick to the binary, which as of now is not implemented in BSE! Whoops. 

Not vital, since most people don't care about BBH systemic velocities (in GCs most PPISN BHs will form as single stars or in wide binaries, so this I don't think this will affect BBH retention very much). But something we should consider adding, as PPISN binaries from the field will likely get ejected from galaxies more readily...

**Comment by katiebreivik** [comment]
@michaelzevin: is this something we need for V3.0.0?

**Comment by michaelzevin** [comment]
@katiebreivik No, I don't want to deal with it by then. It'll take some serious work, I think, since none of the PPISN stuff happens in a function where kick.f is ever called.

**Comment by katiebreivik** [comment]
> @katiebreivik No, I don't want to deal with it by then. It'll take some serious work, I think, since none of the PPISN stuff happens in a function where kick.f is ever called.

Ok totally makes sense - we might want to make a note in the docs that this doesn't happen.

**Comment by michaelzevin** [comment]
FYI, I got around the checking the Blauuw kicks from PPI today. We do incorporate this mass loss in the changes to the orbital parameters, but we don’t currently track it for Vsys.

**Comment by michaelzevin** [comment]
We checked hrdiag.f and kick.f in evolv2, and see that the pre-SN mass is `mass(k)`,  which isn't changed in the hrdiag call. So the systemic velocity calculations in kick.f do indeed account for the mass loss from both the SN and PPI mass loss.
