### ISSUE TITLE
pisn=0 returns error

### ISSUE THREAD

**Issue by astridlamberts** [COSMIC-PopSynth/COSMIC#336]
Hi, I've just tried a COSMIC population run with pins=0 (I don't want PISN, and followed the params.ini instructions) and I got : 

Traceback (most recent call last):
  File "/beegfs/home/alamberts/.conda/envs/cosmic/bin/cosmic-pop", line 106, in <module>
    utils.error_check(BSEDict, filters, convergence, sampling)
  File "/beegfs/home/alamberts/.conda/envs/cosmic/lib/python3.7/site-packages/cosmic/utils.py", line 838, in error_check
    raise ValueError("'{0:s}' needs to be set to either greater than 0 or equal to -1, -2, or -3 (you set it to '{1:0.2f}')".format(flag, BSEDict[flag]))
ValueError: 'pisn' needs to be set to either greater than 0 or equal to -1, -2, or -3 (you set it to '0.00')

I guess this should be fixed?

thanks,

Astrid

**Comment by scottcoughlin2014** [comment]
@astridlamberts Thanks for the issue! We have release `v3.2.0` which fixes this error checking as well as fixes a couple bugs and is the version that is used in the COSMIC paper that is about the be submitted: https://pypi.org/project/cosmic-popsynth/3.2.0/
