### ISSUE TITLE
Minimum run time (tphysf) limited to 1 Myr

### ISSUE THREAD

**Issue by astroJeff** [COSMIC-PopSynth/COSMIC#340]
If, for whatever reason, I want to run a binary for less than 1 Myr, cosmic rounds up and ends up giving me and output at 1 Myr. Ideally, this limitation does not occur, so I could, if I wanted, run a binary for 0.1 Myr. Minimum working example below.

```
from cosmic.sample.initialbinarytable import InitialBinaryTable
from cosmic.evolve import Evolve

m1 =6.242963173038605
m2 = 2.1269020737706663
porb =4900.260678899167
ecc = 0.8803069620359644
tphysf = 0.5
k1 = 1
k2 = 1
z = 0.02

single_binary = InitialBinaryTable.InitialBinaries(m1=m1, 
                                                   m2=m2, 
                                                   porb=porb, 
                                                   ecc=ecc, 
                                                   tphysf=tphysf, 
                                                   kstar1=1, 
                                                   kstar2=1, 
                                                   metallicity=z)

BSEDict = {
    'xi': 0.5,
    'bhflag': 1,
    'neta': 0.5,
    'windflag': 3,
    'wdflag': 0,
    'alpha1': 0.5,
    'pts1': 0.001,
    'pts3': 0.02,
    'pts2': 0.01,
    'epsnov': 0.001,
    'hewind': 1,
    'ck': -1000,
    'bwind': 0.0,
    'lambdaf': 0.5,
    'mxns': 2.5,
    'beta': -1,
    'tflag': 1,
    'acc2': 1.5,
    'nsflag': 3,
    'ceflag': 0,
    'eddfac': 1.0,
    'ifflag': 0,
    'bconst': -3000,
    'sigma': 150.0,
    'gamma': -2.0,
    'pisn': 45.0,
    'bhsigmafrac': 1.0,
    'polar_kick_angle': 90,
    'qcrit_array': [
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0
    ],
    'cekickflag': 2,
    'cehestarflag': 0,
    'cemergeflag': 0,
    'ecsn': 2.5,
    'ecsn_mlow': 1.4,
    'aic': 1,
    'ussn': 0,
    'sigmadiv': 9999999999999,
    'qcflag': 2,
    'eddlimflag': 0,
    'fprimc_array': [
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0,
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0,
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0
    ],
    'bhspinflag': 0,
    'bhspinmag': 0.0,
    'rejuv_fac': 1.0,
    'rejuvflag': 0,
    'htpmb': 1,
    'ST_cr': 1,
    'ST_tide': 1,
    'bdecayfac': 1,
    'natal_kick_array': [-100] * 6,
}

bpp, bcm, initC = Evolve.evolve(initialbinarytable=single_binary, BSEDict=BSEDict)

print(bpp)
```

**Comment by astroJeff** [comment]
I'm clarifying the issue here. It seems like the first line is always 1 Myr, even if following bcm outputs are less than 1 Myr (if dtp<1). Updated code:

`from cosmic.sample.initialbinarytable import InitialBinaryTable
from cosmic.evolve import Evolve

m1 =6.242963173038605
m2 = 2.1269020737706663
porb =4900.260678899167
ecc = 0.8803069620359644
tphysf = 1.5
k1 = 1
k2 = 1
z = 0.02

single_binary = InitialBinaryTable.InitialBinaries(m1=m1, 
                                                   m2=m2, 
                                                   porb=porb, 
                                                   ecc=ecc, 
                                                   tphysf=tphysf, 
                                                   kstar1=1, 
                                                   kstar2=1, 
                                                   metallicity=z)

BSEDict = {
    'xi': 0.5,
    'bhflag': 1,
    'neta': 0.5,
    'windflag': 3,
    'wdflag': 0,
    'alpha1': 0.5,
    'pts1': 0.001,
    'pts3': 0.02,
    'pts2': 0.01,
    'epsnov': 0.001,
    'hewind': 1,
    'ck': -1000,
    'bwind': 0.0,
    'lambdaf': 0.5,
    'mxns': 2.5,
    'beta': -1,
    'tflag': 1,
    'acc2': 1.5,
    'nsflag': 3,
    'ceflag': 0,
    'eddfac': 1.0,
    'ifflag': 0,
    'bconst': -3000,
    'sigma': 150.0,
    'gamma': -2.0,
    'pisn': 45.0,
    'bhsigmafrac': 1.0,
    'polar_kick_angle': 90,
    'qcrit_array': [
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0
    ],
    'cekickflag': 2,
    'cehestarflag': 0,
    'cemergeflag': 0,
    'ecsn': 2.5,
    'ecsn_mlow': 1.4,
    'aic': 1,
    'ussn': 0,
    'sigmadiv': 9999999999999,
    'qcflag': 2,
    'eddlimflag': 0,
    'fprimc_array': [
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0,
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0,
        2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0, 2.0 / 21.0
    ],
    'bhspinflag': 0,
    'bhspinmag': 0.0,
    'rejuv_fac': 1.0,
    'rejuvflag': 0,
    'htpmb': 1,
    'ST_cr': 1,
    'ST_tide': 1,
    'bdecayfac': 1,
    'natal_kick_array': [-100] * 6,
}

bpp, bcm, initC = Evolve.evolve(initialbinarytable=single_binary, BSEDict=BSEDict, dtp=0.1)

print(bcm)`

Has output:

`  tphys  kstar_1   mass0_1    mass_1      lumin_1     rad_1        teff_1  \
0    1.0      1.0  6.242792  6.242792  1164.390883  3.016220  19501.264899   
0    0.1      1.0  6.242948  6.242948  1157.479620  2.995503  19539.483051   
0    0.2      1.0  6.242931  6.242931  1158.234666  2.997798  19535.188392   
0    0.3      1.0  6.242914  6.242914  1158.992928  3.000094  19530.906060   
0    0.4      1.0  6.242896  6.242896  1159.754411  3.002392  19526.635968   
0    0.5      1.0  6.242879  6.242879  1160.519120  3.004692  19522.378030   
0    0.6      1.0  6.242862  6.242862  1161.287063  3.006994  19518.132160   
0    0.7      1.0  6.242845  6.242845  1162.058243  3.009297  19513.898271   
0    0.8      1.0  6.242828  6.242828  1162.832667  3.011603  19509.676278   
0    0.9      1.0  6.242810  6.242810  1163.610341  3.013910  19505.466095   
0    1.0      1.0  6.242793  6.242793  1164.391269  3.016220  19501.267636   
0    1.1      1.0  6.242776  6.242776  1165.175458  3.018531  19497.080815   
0    1.2      1.0  6.242758  6.242758  1165.962914  3.020845  19492.905547   
0    1.3      1.0  6.242741  6.242741  1166.753642  3.023160  19488.741746   
0    1.4      1.0  6.242723  6.242723  1167.547648  3.025478  19484.589326   
0    1.5      1.0  6.242706  6.242706  1168.344937  3.027798  19480.448203   

   massc_1  radc_1        menv_1  ...  B_0_2  SNkick_1  SNkick_2  Vsys_final  \
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   
0      0.0     0.0  1.000000e-10  ...    0.0       0.0       0.0         0.0   

   SNtheta_final  SN_1  SN_2  bin_state  merger_type  bin_num  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  
0            0.0   0.0   0.0          0         -001        0  

[16 rows x 43 columns]`

**Comment by scottcoughlin2014** [comment]
Accidentally fixed!
