### ISSUE TITLE
When stars go into Contact, they never end RLO

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#343]
Found this little bug when looking at high-mass NS progenitors. Typically, whenever anything "begins RLO" (evol_type == 3), it will subsequently "end RLO" (evol_type == 4). However, when you have two near-equal-mass stars, I've found a number of cases where one of the stars goes into RLO, then immediately comes into contact (evol_type == 5) and initiates a double CE. You can see this happening for the system below. 

![Screen Shot 2020-01-27 at 2 52 51 PM](https://user-images.githubusercontent.com/11998670/73212894-c9433e00-4114-11ea-939c-ae496a373a79.png)

My concern is that it doesn't ever "end RLO" before the next evol_type where it "begins RLO" Note that this _does_ happen when these stars end a CE phase (see the CE that happens later on in the evolution). 

I've attached the initial conditions for this particular binary. 

[initCond.hdf5.zip](https://github.com/COSMIC-PopSynth/COSMIC/files/4119364/initCond.hdf5.zip)

**Comment by scottcoughlin2014** [comment]
OK cool I am on it
