### ISSUE TITLE
Getting rid of Thin Disk / Thick Disk / Bulge in cosmic-pop

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#344]
I think it would be better to have these be more like the SFH inputs of the multidim sampler. It would be nice to let the user specify 2 things: start time and duration of star formation. For example: 

_start=13.7
duration=0_
would be the same as delta burst

_start=10
duration=10_
would be the same as thin disk

@katiebreivik let me know what you think about this. I think we can still say in the documentation what are good representations for the Milky Way's thin disk / thick disk / bulge, but I think these are a little tough to interpret otherwise.

**Comment by katiebreivik** [comment]
I like this idea a lot. I've had a few people get really confused about this so I think it's a great move. I am not able to fix it up until next week probably, so if someone beats me to it I won't be mad. 
However, I'm happy to take it over otherwise!
