### ISSUE TITLE
Documentation on BH mass limits is missing gravitational mass corrections

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#348]
Chirag has found that if you set MXNS or the lower limit of the upper BH mass gap, you see a missing factor of 0.1 that can make it seem like the flags aren't being applied properly. We need to highlight this!

**Comment by scottcoughlin2014** [comment]
We need to decide how much the mass loss really is (i.e. its 10 percent right now if you set MXNS=3.0 you are looking at the smallest black hole being 2.7)

**Comment by michaelzevin** [comment]
For the PPI lower mass, this should still be the core mass (prior to neutrino mass loss). For mxns, we need to first check that the remnant mass (after the NS mass loss prescription) is  >mxns, and otherwise do the BH mass loss.

**Comment by michaelzevin** [comment]
This is fixed in #374
