### ISSUE TITLE
Eddlimflag not set in current cosmic version

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#352]
In #238, we added a flag to using the Eddington-limited winds as in MOBSE. I wasn't seeing changed when activating this flag, so did some digging and found that it was being set incorrectly in evolve.Evolve (it was trying to read it as `_evolvebin.windvars.eddlimflag` when in const_bse it should be read from `_evolvebin.flags.eddlimflag`.  

I'm going to have a PR fixing this soon...

**Comment by katiebreivik** [comment]
Thanks for finding this @michaelzevin !
