### ISSUE TITLE
B_0_1 documentation incorrect

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#354]
Small thing, but just wanted to make sure this gets fixed before the next release. The parameter B_0_1 is described wrong on the docs page (https://cosmic-popsynth.github.io/docs/stable/output_info/index.html). It says that it is the "Initial neutron star magnetic field [{\rm{G}}]" but Claire said that in reality this parameter is actually the "current magnetic field".

**Comment by katiebreivik** [comment]
Good catch!

**Comment by michaelzevin** [comment]
Also, this should be changed from B_0_1 > B0_1 in the documentation
