### ISSUE TITLE
B0_1 does not change in bpp

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#356]
The B0_1 and B0_2 parameters in the bpp array do not change, though they do in  the bcm array. We should have the *current*  values of the B-field in the bpp array.

**Comment by scottcoughlin2014** [comment]
related to #354

**Comment by michaelzevin** [comment]
Also, since in both the bcm and bpp B0 will be the _current_ B-field, we should change these column names to "B_1" and "B_2".
