### ISSUE TITLE
v3.3.0 Documentation Needs

### ISSUE THREAD

**Issue by scottcoughlin2014** [COSMIC-PopSynth/COSMIC#359]
- [ ]  columns names and meanings

- [x]  restart evolution example

- [ ]  example of running cosmic-pop with different time resolutions for certain conditions.

**Comment by michaelzevin** [comment]
Note: we need  to change the description for windflag=3

**Comment by michaelzevin** [comment]
We should also have the default binfrac be 0.7 to match Sana

**Comment by michaelzevin** [comment]
Might be worth having an example BSEDict in the `examples` directory as well

**Comment by michaelzevin** [comment]
Also would be good to have a "How to cite COSMIC" somewhere in the docs

**Comment by scottcoughlin2014** [comment]
**BPP COLUMNS**

RROL ===> RRLO

mass0 do we need this?

renv is it size of the envelope or the full radius to the end of the envelope
renv is only set at the giant branch?
menv same deal check this out

checking omega_spin

check epoch seems like it just is needed interanlly by BSE

**BCM**

mass0
RROL ==> RRLO
epoch needs to go

**Comment by scottcoughlin2014** [comment]
renv and menv is only for a convective envelope and only valid for Z=0.02

```
* A function to estimate the mass and radius of the convective envelope,
* as well as the gyration radius of the envelope.
* N.B. Valid only for Z=0.02!
```
