### ISSUE TITLE
Fix print statements when matching  systems aren't found

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#361]
When matching systems are not found, a statement is spit out in the log file. However,  it doesn't linebreak, so it kind of looks like a jumbled mess when this happens repeatedly: 

After filtering the bcm array for desired systems there were no systems matc hing your request. It is possible you should up to the number of binaries pr ovessed in each iteration, i.e. NstepAfter filtering the bcm array for desir ed systems there were no systems matching your request. It is possible you s hould up to the number of binaries provessed in each iteration, i.e. NstepAf ter filtering the bcm array for desired systems there were no systems matchi ng your request. It is possible you should up to the number of binaries prov essed in each iteration, i.e. NstepAfter filtering the bcm array for desired systems there were no systems matching your request. It is possible you sho uld up to the number of binaries provessed in each iteration, i.e. Nstep (edited)

**Comment by katiebreivik** [comment]
Fixed by #365
