### ISSUE TITLE
Add Sana+2014 prescriptions to independent sampler

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#362]
https://ui.adsabs.harvard.edu/abs/2014ApJS..215...15S/abstract

This is pretty much the standard for sampling. It would be good to have these to compare with the (marginalized) predictions from the multidim sampler.  Hopefully wouldn't be too hard to add this option.

**Comment by katiebreivik** [comment]
I'm going to work from the distributions in Sec 2.1 of this paper: https://ui.adsabs.harvard.edu/abs/2015ApJ...814...58D/abstract and will hopefully have a PR soon!

**Comment by michaelzevin** [comment]
Nice. Are these the ones that are compared to the multidim sampler in that one paper?

Also, should we make this a v3.3 milestone?

**Comment by michaelzevin** [comment]
I also think this should become  our "default" independent sampler...

**Comment by michaelzevin** [comment]
This is addressed in #372.  Once  it is merged we can close.
