### ISSUE TITLE
Print issue when closing files

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#377]
Super minor but was bothering my OCD. 
When there is an error and the open files get closed, it doesn't use linebreaks and is hard to read. It  also looks like it repeats the  print statement for some reason. See the attached  output file.

Rather than: 
ValueError: You have supplied an unknown method to filter out the bpp or bcm array. Known methods are ['binary_state']
Closing remaining open files:dat_kstar1_13_14_kstar2_13_14_SFstart_13700.0_SFduration_0.0_metallicity_0.01.h5...donedat_kstar1_13_14_kstar2_13_14_SFstart_13700.0_SFduration_0.0_metallicity_0.01.h5...done

It would be cleaner as: 
ValueError: You have supplied an unknown method to filter out the bpp or bcm array. Known methods are ['binary_state']
Closing remaining open files:
dat_kstar1_13_14_kstar2_13_14_SFstart_13700.0_SFduration_0.0_metallicity_0.01.h5...done

[output.txt](https://github.com/COSMIC-PopSynth/COSMIC/files/4510477/output.txt)

**Comment by katiebreivik** [comment]
take it up with h5py.

**Comment by michaelzevin** [comment]
Can't fix, this is h5's problem
