### ISSUE TITLE
(Thermal timescale?) mass transfer issue

### ISSUE THREAD

**Issue by astroJeff** [COSMIC-PopSynth/COSMIC#396]
When a massive binary enters RLO, if the accretor is a main sequence star, it seems to be able to accept all of the donated mass. In one particular case, I'm finding 30 Msun is (nearly completely) transferred onto a 35 Msun star over 1500 years. This corresponds to a mass transfer rate of 0.02 Msun/yr, and is almost certainly unphysical. We need to look deeper into how COSMIC deals with thermal timescale mass transfer.

**Comment by astroJeff** [comment]
I looked into this a bit more. From the BSE paper, they calculate the Kelvin-Helmholtz timescale (without reference) as 10^7 M/RL, as opposed to GM^2/RL. In the particular case I was looking, the BSE version is ~2 orders of magnitude shorter than what I'm familiar with. The result is that the star can accept much more mass than I think it ought to be able to.

**Comment by katiebreivik** [comment]
Thanks for checking the paper - I was just about to head to that. It's definitely bad that they do this scaling (and it looks like it fits *ok* to within a factor of 3 for solar mass stars). I can cook up a branch that checks how much this changes. I'll also check the other timescales to be sure we don't have other scalings.

**Comment by katiebreivik** [comment]
oh wait! the Timescale is not quite 10^7 M/RL in BSE it's a bit more complicated:
![Screen Shot 2020-05-14 at 10 45 36 AM](https://user-images.githubusercontent.com/22921809/81955751-1a961100-95d0-11ea-84fb-7df6c0add89c.png)

Comparing to a 1 Msun MS star:
t_KH_BSE = 1e7 * (1) * (1) / (1 * 1) = 1e7
t_KH_true = G * M^2/R*L = 31.3e6
so the difference is ~3

for a 30 Msun star:
t_KH_BSE = 1e7 * (30) * (30) / (9.71 * 2e5) ~ 4634.4 yr
t_KH_true = G * M^2/R*L ~14505.7 yr
difference ~ 3

**Comment by astroJeff** [comment]
It looks like COSMIC does in fact multiply by the extra mass term (or m-m_env). My mistake! As @katiebreivik has said, it's only a factor of ~3 off from the term I'm familiar with.

So maybe the issue is a logical one. I still don't understand how/believe a main sequence star can accept mass at such a high rate. Certainly this is not what StarTrack does. I will keep looking into this.

**Comment by katiebreivik** [comment]
I'm not sure why we don't fix the factor anyways though so I'll still submit the PR. No need to make stuff even more wrong than it needs to be.

**Comment by astroJeff** [comment]
Ok, I figured it out. For some reason, equation 64 in the BSE paper allows 10x the thermal timescale rate to be accreted by a main sequence accretor. When I remove that factor of 10, I get what seem to me to be reasonable values for the particular binary I'm looking at.

Exactly what we choose here will make a large difference in the resulting high mass binary populations - and therefore the BBH merger rates. @katiebreivik, @michaelzevin, @scottcoughlin2014 we ought to discuss this and make a decision about what to do.  In the mean time, I'll put together a PR and we can decide whether we want to accept it or not.

**Comment by katiebreivik** [comment]
Awesome! You were much faster than me at figuring this out - I went the route of checking what Belczynksi+2008 does and it seems much more complicated than what Hurley+2002 does.
