### ISSUE TITLE
Controlling the kick of a specific star

### ISSUE THREAD

**Issue by 1nhtran** [COSMIC-PopSynth/COSMIC#398]
Currently, the natal_kick_array only allows us to control the kick of the first/second SN and not the kick associated with the stars. Has the option to directly control the kicks of the stars been considered?

**Comment by michaelzevin** [comment]
Hi @1nhtran I'm not sure I understand, what do you mean by the kick associated with the stars?

**Comment by michaelzevin** [comment]
We've cleared this up. The request is to have the first row of the natal kick array map to the primary star (whether or not it goes SN first) and the second row of the natal kick array will be for the  secondary star.

**Comment by scottcoughlin2014** [comment]
@1nhtran this has been addressed and is now the natal_kick_array feature : see https://github.com/COSMIC-PopSynth/COSMIC/pull/402
