### ISSUE TITLE
Finalizing the ini file

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#400]
From Monica: 

neta = 0.1 (I asked Aaron and he said this is likely the value POSYDON will use)
beta=1./8. (I only have this set because I found that MESA uses 1/8 when calculating bondi-h accretion. This doesn’t mean that they are right. I am also going tested with -1)
qcflag=4 (but I will also test different values)
eddfac=8.77 (Jeff has shared my notes on this)

**Comment by scottcoughlin2014** [comment]
Superseded by #433
