### ISSUE TITLE
correctly calculate the omega parameter resulting from the first SN

### ISSUE THREAD

**Issue by scottcoughlin2014** [COSMIC-PopSynth/COSMIC#429]
@michaelzevin @astroJeff This is where we can discuss and finalize this 3.4 goal

**Comment by michaelzevin** [comment]
![omega_pg1](https://user-images.githubusercontent.com/11998670/94604931-f9238200-025d-11eb-90dc-0064a37c615e.jpg)
![omega_pg2](https://user-images.githubusercontent.com/11998670/94604943-fe80cc80-025d-11eb-8270-4d29b58089b1.jpg)
