### ISSUE TITLE
Params file needs to be updated for 3.4

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#433]
We currently don't have a grflag in the Params.ini file. We should make sure that we have a working Params.ini file for 3.4.

**Comment by scottcoughlin2014** [comment]
Make the examples inifile and bsedict in docs all the same

**Comment by scottcoughlin2014** [comment]
`ecsn` = 2.25
`ecsn_mlow` = 1.6

**Comment by scottcoughlin2014** [comment]
Go into validate BSE dict in utils.py and check for kickflag=-3 and make sure that it corresponds with specific ecsn_mlow to ecsn_high

**Comment by scottcoughlin2014** [comment]
For certain kickflags we will forceably update the ecsn range to match the Mapelli paper range and alert the user.
