### ISSUE TITLE
Core mass used to describe electron capture supernovae produced by naked He stars

### ISSUE THREAD

**Issue by JRGarza** [COSMIC-PopSynth/COSMIC#438]
The issue is, for naked He stars the value of the CO core mass is used to describe the electron capture supernova (ECSN) prescription given (Giacobbo & Mapelli, 2020), while such prescription depends on the mass of the He core at the base of the AGB. 

The code considers that all compact objects born from a naked He star with a CO core mass in the range of [ 1.4 , 2.5 ] Msun are born from ECSN. Such scenario is not compatible with (Giacobbo & Mapelli, 2020) that states that CO cores with a mass of 1.38 Msun are the ones that produce an ECSN. 

@ssbvr @tassos25

https://github.com/COSMIC-PopSynth/COSMIC/blob/e8d2526112a445ec2c086242c76a033da9c842ab/cosmic/src/hrdiag.f#L958-L959

**Comment by scottcoughlin2014** [comment]
@JRGarza thanks for pointing this out, we will update the default value for the Params.ini to reflect that CO range from Giacobbo & Mapelli, thanks!

**Comment by katiebreivik** [comment]
linking in #433 here as well as noting that the plan is to set ecsn and ecsn_mlow to the Giacobbo & Mapelli range and send out a warning that ecsn/ecsn_mlow are being updated to be consistent with the paper.
