### ISSUE TITLE
We lost timestep_conditions when we did the cmc integration

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#461]
In #420 we added check_dtp as a common variable but I don't think it is set for the case where timestep_conditions are specified. I think that all we need to do is set check_dtp somewhere in the evolv2.f based on the checkstate_array.

**Comment by katiebreivik** [comment]
Found it! 

https://github.com/COSMIC-PopSynth/COSMIC/blob/74ccbd70d7e1af1c14bde46bb83836bcfb6f2767/cosmic/checkstate.py#L74

https://github.com/COSMIC-PopSynth/COSMIC/blob/74ccbd70d7e1af1c14bde46bb83836bcfb6f2767/cosmic/checkstate.py#L87

In the above two places, we forgot to update the common block definitions to check_dtp instead of checkstate_array

**Comment by scottcoughlin2014** [comment]
#462 fixes this
