### ISSUE TITLE
BSE inifile dict

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#48]
Auto generate dict from inifile instead of explicitly parsing the file in the runFixedPop executable; maybe loop through file and read in each line to do the auto generating part

**Comment by scottcoughlin2014** [comment]
#55 Is addressing this problem

**Comment by scottcoughlin2014** [comment]
#58 Is needed to shore this up and make sure the dict works with the rest of the code

**Comment by scottcoughlin2014** [comment]
I am going to close this
