### ISSUE TITLE
porb_max samplers for CMC

### ISSUE THREAD

**Issue by carlrodriguez** [COSMIC-PopSynth/COSMIC#480]
Right now if the maximum allowed orbital period for a binary (set by the hard/soft boundary in the cluster) is less than the minimum of the distribution for the log-uniform, we set porb_max = porb_min, consistent with CMC.  This also needs to be checked for the other samplers to make sure the behavior is well-defined (this is just a reminder to myself, so assign it to me).

**Comment by scottcoughlin2014** [comment]
#505 fixed this
