### ISSUE TITLE
Issues with generating black holes with cosmicpop at near-Solar metallicity

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#487]
There are a couple issues I've had in some runs, I'll try to list them logically below. The population run directory is on Quest at `/projects/b1095/michaelzevin/cosmic/populations/acc_efficiency/acclim_1/0.017`

1. When I ran this population using the multidim sampler, it wasn't finding _any_ black holes. This seems odd to me, but could _maybe_ be due to the initial conditions? So I ran with the independent sampler using `q_min=0.1`. However, I hope this will instead get fixed from addressing the issues below, since in versions of COSMIC from last summer I was still getting BBHs at Solar metallicity. 

2. When rerunning using the independent sampler, the model generated 54 matching BBH systems on the first step (which I saw in the log). However, it did not acquire **any** more systems in the rest of the run, which had a wall time of 5 days. I've attached the `.dat` file with these 54 systems. 

3. When the run hit its wall time of 5 days, rather than writing this in the `.out` file, it seems to have overwritten the `log` and `.out` files completely (i.e., they're empty). 

[dat_kstar1_14_kstar2_14_SFstart_13700.0_SFduration_0.0_metallicity_0.017.h5.zip](https://github.com/COSMIC-PopSynth/COSMIC/files/6131099/dat_kstar1_14_kstar2_14_SFstart_13700.0_SFduration_0.0_metallicity_0.017.h5.zip)

**Comment by katiebreivik** [comment]
This was happening because cosmic-pop had a few continue statements which bumped the code out of the loop before Nstep was updated. This means that the same seed was run over and over forever and failed to produce any new systems. This has been fixed in PR: #493
