### ISSUE TITLE
mxns for merging neutron stars

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#500]
Camille has supposed found some cases where two NS merge and form a BH, even though the merger product is lower than `mxns=3`. 

This is her example: 
`/projects/b1095/cliotine/cosmic_output/cosmic_3.3/Mike_param_runs/pessimistic_CE_runs/new_DCO_pops/runs/0.00309496/dat_kstar1_13_14_kstar2_13_14_SFstart_13700.0_SFduration_0.0_metallicity_0.00309496.h5`
`bin_num = 1010925`

**Comment by scottcoughlin2014** [comment]
Look into collision matrix...change one line in mix.f

**Comment by scottcoughlin2014** [comment]
Fix in #503
