### ISSUE TITLE
Compiling COSMIC with Big Sur

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#501]
To compile COSMIC on Big Sur OS, I have to use the following line: 

`LDFLAGS="-L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" python setup.py build_ext`

**Comment by michaelzevin** [comment]
Look into collision matrix...

**Comment by scottcoughlin2014** [comment]
solved in #502
