### ISSUE TITLE
problem reproducing single-system binary evolution exactly

### ISSUE THREAD

**Issue by celiotine** [COSMIC-PopSynth/COSMIC#520]
In this directory: `/projects/b1095/cliotine/cosmic_output/cosmic_3.3/Mike_param_runs/pessimistic_CE_runs/new_DCO_pops/runs/0.00093378`
there is a script `evolve_test.py` that re-evolves a binary from the COSMIC initCond file using Evolve.evolve. The following is the re-evolved kick_info compared to the original kick_info from COSMIC (you can run the full script for more information):

**COSMIC kicks:** 
  ```
 star  disrupted  natal_kick        phi       theta  ...  vsys_2_total  delta_theta_total  omega    randomseed  bin_num
7   1.0        0.0         0.0  53.125601  177.840714  ...           0.0                0.0    0.0 -4.313532e+08      7.0
7   2.0        0.0         0.0   5.362697  247.016473  ...           0.0                0.0    NaN  1.645811e+09      7.0
```

**re-evolved kicks:** 
   ```
star  disrupted  natal_kick        phi       theta  ...  vsys_2_total  delta_theta_total  omega    randomseed  bin_num
7   1.0        1.0  655.421844 -26.980760  105.550568  ...    101.381279                0.0    0.0 -4.313532e+08      7.0
7   2.0        1.0  151.809732 -61.374641  271.515920  ...    217.669646                0.0    0.0  1.455352e+09      7.0
```

Notice the difference between the two. Why is this happening?

**Comment by michaelzevin** [comment]
This issue was fixed by #526, just required a 1-line change and adding a .copy()
