### ISSUE TITLE
`params` not in args namespace, but still being fed to independent sampler

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#522]
See error being spit out at `/projects/b1095/cliotine/cosmic_output/cosmic_3.3/Mike_param_runs/pessimistic_CE_runs/new_DCO_pops/runs/test_run/bbh_pop.err`

Looks like it's trying to pass an argument to the independent sampler that isn't defined. Maybe because of some name change in the ini file? Tried to figure out what this is supposed to be, but no dice.

**Comment by katiebreivik** [comment]
Dang. `args.params` Is supposed to be `args.inifile`

Sorry!! Will fix tonight!
