### ISSUE TITLE
Speed up set_reff

### ISSUE THREAD

**Issue by carlrodriguez** [COSMIC-PopSynth/COSMIC#533]
The current set_reff function is EXTREMELY slow, since it's technically calling COSMIC for all the binaries in the initial conditions and spooling up the entire python machinery.

It would be relatively easy to write a quick wrapper to star/hrdiag to just call those functions only, bypassing calling evolv2 and all the python overhead.  Should speed up CMC and independent samplers significantly.

**Comment by carlrodriguez** [comment]
Ok the new commit I've made does this; doing it all in fortran speeds things up by 60x

**Comment by scottcoughlin2014** [comment]
Finished in #536
