### ISSUE TITLE
Replace get_velocities in elson.py

### ISSUE THREAD

**Issue by carlrodriguez** [COSMIC-PopSynth/COSMIC#534]
right now the get_velocities throws some integration warnings when sampling from an Elson profile, largely because when numerically integrating the distribution function, you get a lot of roundoff error when the energy goes to zero.  this is fine, especially for a generic Elson profile, but the Plummer profile (which is Elson when gamma=4) has an analytic distribution function that can be sampled directly, and would be a lot faster and not throw errors (which don't effect the results, but looks sloppy).

Carl, put in a special case function to draw from that distribution function when gamma=4

**Comment by carlrodriguez** [comment]
This is done in the latest PR

**Comment by carlrodriguez** [comment]
So somehow this code never made it in?  And the PR that supposedly fixed this is empty.  Not sure what happened, but I'm going to have to code this up again and do another PR.

**Comment by TomWagg** [comment]
@carlrodriguez does this belong in the CMC repo now? (I'm cleaning up old issues)

**Comment by carlrodriguez** [comment]
The CMC IC files are here so we will still likely get bug reports for them here, but this issue is fixed so I'll close it.

**Comment by katiebreivik** [comment]
Thanks @carlrodriguez !
