### ISSUE TITLE
Track bcm array params at specific times 

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#59]
runFixedPop currently only takes the final output of the bcm array (at tphys=tphysf). If you want the value of a parameter at a specific time, e.g. the semi-major axis before the 2nd SN in a BNS progenitor, you need to use the time resolution built into the evolve class using the dtp kwarg, where dtp is the timestep in Myr that BSE uses to write the bcm array.

This could hopefully be generalized to not just be for the 2nd SN, but I'm not sure how to do that. It should also be accessed with a command line argument.

**Comment by scottcoughlin2014** [comment]
@katiebreivik along these lines we also have a filtering problem to go along with the fact that `dtp` keyword argument is not actually used in the `runFixedPop` executable anywhere

```
265         bcm_save_filtered = bcm_filtered.loc[(bcm_filtered.kstar_1.isin(kstar1_range)) & (bcm_filtered.kstar_2.isin(kstar2_range))]
```
This line designed to filter out the *final* kstar states of the `bcm` i.e.  at tphys=tphysf like you said would potentially through out discete times steps from the `bcm` once we add in the `dtp` into `runFixed`Pop`
