### ISSUE TITLE
Mass transfer from white dwarf donors

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#60]
cosmic (and BSE in general) doesn't handle mass transfer calculations very well. Since we rely on Monte Carlo samples to build Galaxy populations, and the binary parameters during mass transfer from a white dwarf (WD) are unique; we run into problems. 

We need to update runFixedPop to filter for mass transfer from WDs if the user wants to include mass transferring systems in their population. We also need to update gxRealization include the data bases of evolutionary tracks from @kylekremer23's mass transfer evolution code to generate a Galactic population of mass-transferring systems with WD donors.

**Comment by scottcoughlin2014** [comment]
@katiebreivik I am guessing the filtering updates has addressed this issue? can we close?

**Comment by scottcoughlin2014** [comment]
@katiebreivik we can close this right?

**Comment by scottcoughlin2014** [comment]
Kyle and Katie can be contacted if this is something someone desires.
