### ISSUE TITLE
FIRE SFH requires large data

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#62]
I'm not sure how to handle hosting a large data file (~750 Mb) that we need to access for the FIRE Galaxy work.

The data set contains the columns: [tborn, metallicity, xGx, yGx, zGx, distance, kern_len] where:
tborn : birth time in Gyr where beginning of Universe is at tborn=0
metallicity : Z/Z sun
xGx, yGx, zGx : x,y,z positions in kiloparsecs with (0,0,0) at Galactic center
distance : distance from Galactic center in kpc
kern_len : used to sample position where the position is sampled from gaussian at x,y,z with widt of kern_len

The idea is that we sample a metallicity and birth time (along with other binary parameters);
then find the row in the data set that is closest to the sampled metallicity and birth time;
then assign the binary a position by sampling from a gaussian centered at the xGx, yGx, zGx values with width kern_len.

I think this works better than generating a kde from a 6 column by ~13 million row data set? 

Very open to suggestions! any ideas? 
@scottcoughlin2014 @cplb @cpankow @orlox @michaelzevin @kylekremer23 @chasebk

**Comment by scottcoughlin2014** [comment]
Under the free github we can handle large files up to 1 Gigabyte with GitHub's LFS. In terms of how best to handling obtaining position values utilizing that information, I think other may have more interesting ideas. Is this file on quest?

**Comment by katiebreivik** [comment]
@scottcoughlin2014 It is not on quest. I just have it locally right now and I don't have access to quest right now 👎

**Comment by scottcoughlin2014** [comment]
Email GITHUB about making COSMIC a Educational Organization.

**Comment by katiebreivik** [comment]
I worked this out and will submit a PR over the next little while (couple weeks) that implements an MC sample for the Galactic positions. I'm waiting to see about switching cosmic's hosting to the CIERA github and whether or not we are going to get an educational account.

**Comment by scottcoughlin2014** [comment]
This is now the FIRE's team problem. They will make queryable databse
