### ISSUE TITLE
bcm/bpp array doesn't have metallicity information

### ISSUE THREAD

**Issue by katiebreivik** [COSMIC-PopSynth/COSMIC#66]
For the FIRE star formation history, we need to have both the birth time and the metallicity for each binary. I think the thing that makes the most sense is to add the metallicity of the binary to both the bcm and bpp arrays

**Comment by scottcoughlin2014** [comment]
@katiebreivik where are we at on this?

**Comment by michaelzevin** [comment]
@katiebreivik shouldn't this be in the initCond file, as it currently is now?
