### ISSUE TITLE
Problem with 'independent' and 'multidim' population sampling methods

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#76]
I've been working to generate some binary populations with cosmic to evolve and have noticed what I think are a few bugs and unclear things in the population sampling methods: 

1. If you specify final_kstar1 and final_kstar2 with the independent sampling method, it'll bug out I think because a list wasn't converted to an array. In fact, this will happen if you run the exact line in the documentation: 
`InitialBinaries, sampled_mass, n_sampled = InitialBinaryTable.sampler('independent', final_kstar1, final_kstar2, primary_model='kroupa93', ecc_model='thermal', SFH_model='const', component_age=10000.0, met=0.02, size=10000)`

2. If instead of specifying the kstars you specify m_min and m_max, `InitialBinaryTable` won't spit out the same number of outputs as is you specify final_kstar1 and final_kstar2 (I think it's missing n_sampled or sampled_mass). I think it would be best to output the same stuff whether you specify final_kstar or max/min mass. 

3. In the multidim sampler, `InitialBinaryTable.sampler('multidim', ...)` only spits out 2 outputs as well, so if you run the sample code from the documentation (`InitialBinaries, sampled_mass, n_sampled = InitialBinaryTable.sampler('multidim', [11], [11], 2, 1, 'const', 10000.0, 0.02, 10)`) it will also fail.

**Comment by scottcoughlin2014** [comment]
@michaelzevin responses in line

I've been working to generate some binary populations with cosmic to evolve and have noticed what I think are a few bugs and unclear things in the population sampling methods:

    If you specify final_kstar1 and final_kstar2 with the independent sampling method, it'll bug out I think because a list wasn't converted to an array. In fact, this will happen if you run the exact line in the documentation:
    InitialBinaries, sampled_mass, n_sampled = InitialBinaryTable.sampler('independent', final_kstar1, final_kstar2, primary_model='kroupa93', ecc_model='thermal', SFH_model='const', component_age=10000.0, met=0.02, size=10000)

- I can fix this, yes one should be able to specify this as an `int` and a `list`.

    If instead of specifying the kstars you specify m_min and m_max, InitialBinaryTable won't spit out the same number of outputs as is you specify final_kstar1 and final_kstar2 (I think it's missing n_sampled or sampled_mass). I think it would be best to output the same stuff whether you specify final_kstar or max/min mass.

- Do we want this functionality? If we do then we need to change some thngs because `InitialBinaryTable.sampler('independent')` does not take `m_min` and `m_max` as even possible arguments so I am not sure what you were attempting or how you even got outputs.

    In the multidim sampler, InitialBinaryTable.sampler('multidim', ...) only spits out 2 outputs as well, so if you run the sample code from the documentation (InitialBinaries, sampled_mass, n_sampled = InitialBinaryTable.sampler('multidim', [11], [11], 2, 1, 'const', 10000.0, 0.02, 10)) it will also fail.

-I think that seems fair
