### ISSUE TITLE
Redshift Not in BCM or BPP?

### ISSUE THREAD

**Issue by scottcoughlin2014** [COSMIC-PopSynth/COSMIC#83]
@katiebreivik am I missing something? We should add that in.

Scotty

**Comment by katiebreivik** [comment]
We should make this very clear; e.g. explain explicitly what the birth time of the binary is, what tphys means, that tphys is the time today.

**Comment by michaelzevin** [comment]
Opening a new issue for expanding docs about tphys and birth time.
