### ISSUE TITLE
add merger_type series to bcm array

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#88]
Create a merger_type column in the bcm array. This should be set to a default value of -1. The merger type will be specified as a combination of the kstar types (always with a minimum of 2 digits for each kstar type). 

For example, a BH-BH merger will have a merger_type value of 1414, a helium white dwarf with a giant branch naked helium star will be 1009, and a deeply or fully convective low mass MS star with a main sequence star will be 0001.

**Comment by scottcoughlin2014** [comment]
It would be nice to have more examples to test this. But here is a start. Also this new methodlogies means that `1413` get captures correctly where as before I was setting `binstate=14` for those with previous method. Thanks to @michaelzevin for the pointer
```
(cosmic-py36) [sbc538@quser11 debug]$ bash run_all_merger_systems.sh 
          tphys  kstar_1    mass0_1     mass_1  lumin_1   ...     formation_1  formation_2  bin_state  merger_type  bin_num
0  10114.768555     14.0  13.792748  25.247549    -10.0   ...             4.0          4.0        1.0       1414.0        0

[1 rows x 39 columns]
        tphys  kstar_1   mass0_1  mass_1   lumin_1   ...     formation_1  formation_2  bin_state  merger_type  bin_num
0  10118.8125     15.0  1.429424     0.0 -8.373529   ...             4.0          5.0        1.0       1313.0        0

[1 rows x 39 columns]
         tphys  kstar_1   mass0_1    mass_1  lumin_1   ...     formation_1  formation_2  bin_state  merger_type  bin_num
0  3288.084717     14.0  7.805439  4.697084    -10.0   ...             4.0          4.0        1.0       1314.0        0

[1 rows x 39 columns]
         tphys  kstar_1     mass0_1      mass_1    lumin_1   ...     formation_1  formation_2  bin_state  merger_type  bin_num
0     0.068922      1.0  112.169884  112.169884   6.201618   ...             0.0          0.0        0.0         -1.0        0
0  1175.699097     15.0    9.085922    0.000000 -10.000000   ...             4.0          4.0        1.0       1413.0        0
```

**Comment by scottcoughlin2014** [comment]
@katiebreivik Perhaps you could email me a file that would include mergers with `kstar1=9` and `kstar2=9` or something to test that those get set to `0909` correctly.

**Comment by scottcoughlin2014** [comment]
#89 addresses this
