### ISSUE TITLE
Match function has issues when you are trying to do something silly

### ISSUE THREAD

**Issue by scottcoughlin2014** [COSMIC-PopSynth/COSMIC#92]
Hey @katiebreivik ,

I realize that the title makes it seem like nothing is really wrong but it could be a common mistake. For instance working ont he filtering for merger_type and bin_state branch I kept running into errors in the `Match` function, well it was because I was still asking for `porb` and `ecc` convergence per the defaults. Obviously `ecc` is set to `-1` for all merged systems and `porb` is all negative values. This seems to mess with the Match function. Perhaps we can a.) resolves this on the Match side. Or maybe better we see what people are tryingt o ask for (like bin_state ==1) and say "Hey you know you are asking for convergence on silly columns right?"

**Comment by katiebreivik** [comment]
This is fixed [here](https://github.com/COSMIC-PopSynth/COSMIC/pull/107)
