### ISSUE TITLE
Updating documentation with SN flags

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#95]
The `formation_1` and `formation_2` series in the bcm array (which will be changed to the names `SN_1` and `SN_2`) have integers to specify which type of supernova happened. From talking with Claire, we know the following: 

4: Fe CCSN (your standard Iron core collapse SN)
5: Evolution Induced Collapse (i.e., electron capture supernova)
6: Accretion Induced Collapse (i.e., a white dwarf accretes material until it is super-Chandrasekhar and collapses into a neutron star)
7: Merger Induced Collapse (i.e., same as above but due to a merger rather than accretion)

This might not be all-encompassing, we should check if other flags can be set for `formation_1` and `formation_2`. 

Also, I think 0 specifies a merger or collision, which is probably not necessary to include anymore as we have the `merger_type` series now. I'd recommend having a stock value of -1 if a SN doesn't happen.

**Comment by scottcoughlin2014** [comment]
ultrastrip flag?
pair instability (may be one but should follow up)?
pulsational pair instability?

**Comment by scottcoughlin2014** [comment]
@scottcoughlin2014 you a `git grep` to find everyplace formation 1 and 2 are set

**Comment by michaelzevin** [comment]
Done in #230
